### ISSUE TITLE
[Vssue]/install/install-k8s-dashboard.html

### ISSUE THREAD

**Issue by shaohq** [eip-work/kuboard-press#126]
https://kuboard.cn/install/install-k8s-dashboard.html

**Comment by shaohq** [comment]
Kuboard - 快速在 Kubernetes 上落地微服务

**Comment by WinterChenS** [comment]
找到解决方案：
1. 修改ymal文件：
```
kind: Service
apiVersion: v1
metadata:
  labels:
    k8s-app: kubernetes-dashboard
  name: kubernetes-dashboard
  namespace: kube-system
spec:
  type: NodePort     ------添加type
  ports:
    - port: 443
      targetPort: 8443
      nodePort: 30000 ---------添加，这个配置是你可以访问的端口
  selector:
    k8s-app: kubernetes-dashboard
```

2.重点来了，因为没有配置ssl，所以需要使用Firefox浏览器访问
```
https://<ip>:30000
```
这样就可以访问到了

**Comment by 15771707886** [comment]
页面已经出来了，但是输入token之后不能登录是什么情况呢？

**Comment by shaohq** [comment]
你看一下是不是token多了或少了一些字符发自我的华为手机-------- 原始邮件 --------发件人： 15771707886 <notifications@github.com>日期： 2020年2月7日周五 12:46收件人： eip-work/kuboard-press <kuboard-press@noreply.github.com>抄送： shaohq <77128473@qq.com>, Author <author@noreply.github.com>主    题： Re: [eip-work/kuboard-press] [Vssue]/install/install-k8s-dashboard.html (#126)页面已经出来了，但是输入token之后不能登录是什么情况呢？

**Comment by AlanLee97** [comment]
我使用了NodePort的方式可以访问，但是要用火狐浏览器才可以，选择https协议，接受风险就可以进去了

**Comment by sr880828** [comment]
如何配置dashboard和ingress

**Comment by jiang11958** [comment]
k8s dashboard 外网访问NodePort方式测试可行：
https://computingforgeeks.com/how-to-install-kubernetes-dashboard-with-nodeport/

**Comment by zjcnew** [comment]
这里官方dashboard方式方式http://localhost:8001/api/v1/namespaces/kubernetes-dashboard/services/https:kubernetes-dashboard:/proxy/改成支持其他主机能够访问的方式，需要怎么配置。

**Comment by invince** [comment]
不知道为什么我这里一定要： http://localhost:8001/api/v1/namespaces/kubernetes-dashboard/services/https:kubernetes-dashboard:https/proxy/ 再加个https才能访问
我是通过helm安装的dashboard

**Comment by morya** [comment]
这篇文档貌似和实际使用已经脱节，照着文档配置不生效。

同时，直接改容器里面的 `/usr/share/nginx/html/kuboard-namespace-layout-v1.yaml` 文件倒是可以

但color字段无法生效

```
cat kuboard-namespace-layout-v1.yaml
version: "v1"

layers:
  - prefix: web
    name: "front"
    enName: "web"
    color: "blue"
```
