### ISSUE TITLE
更改ingress路径失败

### ISSUE THREAD

**Issue by hbstarjason** [eip-work/kuboard-press#153]
想做2项修改：
1、默认的kuboard.yaml里所有的资源，安装在了kube-system的namespace。想替换成另外的namespace是否可以呢？是否有特殊的要求必须要放在kube-system？
2、想替换掉ingress的path，尝试修改为/kuboard，但是访问似乎有问题，是做了特殊的处理吗？
修改内容如下：
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: kuboard
  namespace: kuboard
  annotations:
    nginx.org/websocket-services: "kuboard"
    nginx.com/sticky-cookie-services: "serviceName=kuboard srv_id expires=1h path=/kuboard"
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host:  kuboard.local
    http:
      paths:
      - path: /kuboard
        backend:
          serviceName: kuboard
          servicePort: http
  tls:
    - hosts:
        - kuboard.local
      secretName: tls-secret-kuboard
```
