### ISSUE TITLE
kuboard编辑服务保存导致注解丢失（prometheus）

### ISSUE THREAD

**Issue by alfredking12** [eip-work/kuboard-press#336]
问题现象和步骤：
1. 通过kuboard编辑Deployment的YAML配置，配置pod template 注解（增加prometheus相关注解），查看Deployment的YAML文件注解增加有效
```yaml
spec:
  template:
    metadata:
      annotations:
        prometheus.io/path: /actuator/prometheus
        prometheus.io/scrape: 'true'
```
2. 通过kuboard编辑服务，点击保存
3. 查看Deployment的YAML文件中注解丢失

问题分析：
使用kuboard编辑服务并保存后，会导致Deployment丢失pod template的注解。查看对应的HTTP请求如下：
1. 发送Deployment查询请求
```http
GET http://ip:32567/k8s-api/apis/apps/v1/namespaces/{namespace}/deployments/{name}
```
2. 应答如下（对原数据做过精简）
```yaml
{
  "kind": "Deployment",
  "apiVersion": "apps/v1",
  "metadata": {
    "name": "name",
    "namespace": "namespace"
    
  },
  "spec": {
    "replicas": 1,
    "selector": {
      "matchLabels": {
        "k8s.kuboard.cn/name": "name"
      }
    },
    "template": {
      "metadata": {
        "creationTimestamp": null,
        "labels": {
          "k8s.kuboard.cn/name": "name"
        },
        "annotations": {
          "prometheus.io/path": "/actuator/prometheus",
          "prometheus.io/scrape": "true"
        }
      },
      "spec": {
        "containers": [
          {
            "name": "name",
            "image": "image:latest"
          }
        ]
      }
    }
  }
}
```

3. 发送Deployment更新请求（注意：丢失了annotation）
```yaml
{
  "kind": "Deployment",
  "apiVersion": "apps/v1",
  "metadata": {
    "name": "name",
    "namespace": "namespace"
    
  },
  "spec": {
    "replicas": 1,
    "selector": {
      "matchLabels": {
        "k8s.kuboard.cn/name": "name"
      }
    },
    "template": {
      "metadata": {
        "creationTimestamp": null,
        "labels": {
          "k8s.kuboard.cn/name": "name"
        }
      },
      "spec": {
        "containers": [
          {
            "name": "name",
            "image": "image:latest"
          }
        ]
      }
    }
  }
}
```

K8S版本：
v1.23.6+k3s1
