### ISSUE TITLE
1.25版本的K8S安装之后没有生成token，无法登陆！

### ISSUE THREAD

**Issue by XiongGG1989** [eip-work/kuboard-press#424]

**Comment by simpsed** [comment]
解决了嘛，1.23也这样

**Comment by XiongGG1989** [comment]
> 解决了嘛，1.23也这样
目前我的做法是手动生成一个token，绑定到kuboard创建的sa上！
apiVersion: v1
kind: Secret
metadata:
  name: kuboard-viewer #自己定义，可以和kuboard的sa账号保持一致，这样容易区分！
  namespace: kube-system
  annotations:
    kubernetes.io/service-account.name: "kuboard-viewer" #填写kuboard的sa账号，kuboard-viewer绑定的是只读权限，kuboard-user绑定的是管理权限，根据需要选择其中一个！
type: kubernetes.io/service-account-token
最后获取token就可以进行访问了！

**Comment by sgl111** [comment]
能再详细一点吗 ，小白很迷茫

**Comment by XiongGG1989** [comment]
> 



> 能再详细一点吗 ，小白很迷茫
新建配置文件！
`vim kuboard-token.yaml`
`apiVersion: v1
kind: Secret
metadata:
  name: kuboard-viewer
  namespace: kube-system
  annotations:
    kubernetes.io/service-account.name: "kuboard-viewer"
type: kubernetes.io/service-account-token`
最后apply
`kubectl apply -f kuboard-token.yaml`
执行完成就可以获取token了！
`echo $(kubectl -n kube-system get secret $(kubectl -n kube-system get secret | grep ^kuboard-viewer | awk '{print $1}') -o go-template='{{.data.token}}' | base64 -d)`

**Comment by XiongGG1989** [comment]
> 能再详细一点吗 ，小白很迷茫

新建配置文件！
`vim kuboard-token.yaml`
将以下内容添加进去：
```
apiVersion: v1
kind: Secret
metadata:
  name: kuboard-viewer
  namespace: kube-system
  annotations:
    kubernetes.io/service-account.name: "kuboard-viewer"
type: kubernetes.io/service-account-token
```
最后apply
`kubectl apply -f kuboard-token.yaml`
执行完成就可以获取token了！
`echo $(kubectl -n kube-system get secret $(kubectl -n kube-system get secret | grep ^kuboard-viewer | awk '{print $1}') -o go-template='{{.data.token}}' | base64 -d)`
