### ISSUE TITLE
kuboard-agent 和 kuboard-agent-2 在OrbStack v1.6.0+启动失败

### ISSUE THREAD

**Issue by bostin** [eip-work/kuboard-press#556]
异常日志如下:

Start kagent
 
Start nginx
nameserver is [192.168.194.138
nameserver fd07:b51a:cc66:a:8000::a]
sed: unmatched '/'
[GIN-debug] [WARNING] Creating an Engine instance with the Logger and Recovery middleware already attached.

[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
 - using env:	export GIN_MODE=release
 - using code:	gin.SetMode(gin.ReleaseMode)

[GIN-debug] POST   /check-certificates       --> main.checkCerts (3 handlers)
[GIN-debug] Listening and serving HTTP on :5000
2024/11/04 18:19:02 [emerg] 36#36: host not found in resolver "NAMESERVER" in /etc/nginx/conf.d/nginx.80.conf:21
nginx: [emerg] host not found in resolver "NAMESERVER" in /etc/nginx/conf.d/nginx.80.conf:21

**Comment by qkboy** [comment]
在不修改镜像的情况下，可以通过 ConfigMap 导入修改后的脚本，然后替换启动容器时的 EntryPoint 来处理。
```
$ vim kuboard-agent-start-script.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: kuboard-agent-start-script
  namespace: kuboard
data:
  start-kuboard-agent.sh: |
    #!/bin/sh
    
    echo -e "\033[36mKuboardEndpoint           :\033[0m ${KUBOARD_ENDPOINT}"
    echo -e "\033[36mKuboardAgent              :\033[0m ${KUBOARD_AGENT_PROTOCOL}://${KUBOARD_AGENT_HOST}:${KUBOARD_AGENT_PORT}"
    echo -e "\033[36mKUBOARD_AGENT_PROXY       :\033[0m ${KUBOARD_AGENT_PROXY}"
    echo -e "\033[36mKUBOARD_AGENT_KEY         :\033[0m ${KUBOARD_AGENT_KEY}"
    echo -e "\033[36mKUBOARD_K8S_CLUSTER_NAME  :\033[0m ${KUBOARD_K8S_CLUSTER_NAME}"
    echo -e "\033[36mKUBOARD_ANONYMOUS_TOKEN   :\033[0m ${KUBOARD_ANONYMOUS_TOKEN}"
    
    if [ x"${KUBOARD_ENDPOINT}" = x ] || [ x"${KUBOARD_AGENT_HOST}" = x ] || [ x"${KUBOARD_AGENT_PORT}" = x ] || [ x"${KUBOARD_AGENT_KEY}" = x ] || [ x"${KUBOARD_K8S_CLUSTER_NAME}" = x ]     || [ x"${KUBOARD_AGENT_REMOTE_PORT}" = x ]; then
      echo "环境变量 KUBOARD_ENDPOINT / KUBOARD_AGENT_HOST / KUBOARD_AGENT_PORT / KUBOARD_AGENT_KEY / KUBOARD_K8S_CLUSTER_NAME 不能为空"
      exit;
    fi
    
    echo " "
    
    echo -e "\033[36m生成配置\033[0m"
    
    /gen_config
    agent_endpoint_count=$?
    
    if [ x"${agent_endpoint_count}" = "x0" ]; then
      echo "使用环境变量中的参数"
    
      KUBOARD_AGENT_REMOTE_PORT_NGINX=$((${KUBOARD_AGENT_REMOTE_PORT} + 10000))
    
      echo "KUBOARD_AGENT_REMOTE_PORT_NGINX: ${KUBOARD_AGENT_REMOTE_PORT_NGINX}"
    
      sed -i s/KUBOARD_AGENT_REMOTE_PORT_NGINX/"${KUBOARD_AGENT_REMOTE_PORT_NGINX}"/g /etc/kuboard/kuboard-agent.ini
    
      sed -i s/KUBOARD_AGENT_HOST/"${KUBOARD_AGENT_HOST}"/g /etc/kuboard/kuboard-agent.ini
      sed -i s/KUBOARD_AGENT_PORT/"${KUBOARD_AGENT_PORT}"/g /etc/kuboard/kuboard-agent.ini
      sed -i s/KUBOARD_AGENT_REMOTE_PORT/"${KUBOARD_AGENT_REMOTE_PORT}"/g /etc/kuboard/kuboard-agent.ini
      sed -i s/KUBOARD_AGENT_PROTOCOL/"${KUBOARD_AGENT_PROTOCOL}"/g /etc/kuboard/kuboard-agent.ini
      sed -i 's#'''KUBOARD_AGENT_PROXY'''#'''${KUBOARD_AGENT_PROXY}'''#g' /etc/kuboard/kuboard-agent.ini
      sed -i s/KUBOARD_AGENT_KEY/"${KUBOARD_AGENT_KEY}"/g /etc/kuboard/kuboard-agent.ini
      sed -i s/KUBOARD_K8S_CLUSTER_NAME/"${KUBOARD_K8S_CLUSTER_NAME}"/g /etc/kuboard/kuboard-agent.ini
      sed -i s/KUBOARD_API_LOCAL_IP/"${KUBERNETES_SERVICE_HOST}"/g /etc/kuboard/kuboard-agent.ini
      sed -i s/KUBOARD_API_LOCAL_PORT/"${KUBERNETES_SERVICE_PORT}"/g /etc/kuboard/kuboard-agent.ini
      sed -i s/POD_HOST_NAME/"$(hostname)"/g /etc/kuboard/kuboard-agent.ini
    
    fi
    
    KUBERNETES_TOKEN=""
    if [ -f "/run/secrets/kubernetes.io/serviceaccount/token" ]
    then
      read KUBERNETES_TOKEN < /run/secrets/kubernetes.io/serviceaccount/token
    elif [ -f "/var/run/secrets/kubernetes.io/serviceaccount/token" ]
    then
      read KUBERNETES_TOKEN < /var/run/secrets/kubernetes.io/serviceaccount/token
    else
      echo -e "\033[31m未在如下路径找到 token\033[0m"
      echo "/run/secrets/kubernetes.io/serviceaccount/token"
      echo "/var/run/secrets/kubernetes.io/serviceaccount/token"
      exit;
    fi
    
    KUBOARD_AGENT_VERSION=""
    read KUBOARD_AGENT_VERSION < /kuboard-agent-version.json
    
    K8S_VERSION=$(curl -k "https://${KUBERNETES_SERVICE_HOST}:${KUBERNETES_SERVICE_PORT}/version" \
      -H 'Cache-Control: no-cache' \
      -H 'Accept: application/json, text/plain, */*' \
      -H "Authorization: Bearer ${KUBERNETES_TOKEN}" \
      --compressed --insecure)
    
    echo " "
    echo "K8S_VERSION:"
    echo ${K8S_VERSION}
    echo " "
    echo "AGENT_VERSION:"
    echo ${KUBOARD_AGENT_VERSION}
    echo " "
    
    export http_proxy=${KUBOARD_AGENT_PROXY}
    export https_proxy=${KUBOARD_AGENT_PROXY}
    
    postResult=$(curl -k --location --request POST "${KUBOARD_ENDPOINT}/kuboard-api/cluster/${KUBOARD_K8S_CLUSTER_NAME}/kind/KubernetesClusterToken" \
    --header 'Content-Type: application/json' \
    --header 'Accept: application/json' \
    --data-raw "{
        \"kind\": \"KubernetesClusterToken\",
        \"metadata\": {
            \"cluster\": \"${KUBOARD_K8S_CLUSTER_NAME}\",
            \"name\": \"${KUBERNETES_TOKEN_NAME}\",
            \"annotations\": {
                \"description\": \"ServiceAccount Token for Cluster ${KUBOARD_K8S_CLUSTER_NAME}\"
            }
        },
        \"spec\": {
            \"token\": \"${KUBERNETES_TOKEN}\",
            \"anonymousToken\": \"${KUBOARD_ANONYMOUS_TOKEN}\",
            \"agentVersion\": ${KUBOARD_AGENT_VERSION},
            \"kubernetesVersion\": ${K8S_VERSION}
        }
    }")
    
    echo " "
    
    postResultPass=$(echo $postResult | grep "${KUBOARD_AGENT_VERSION}")
    
    if [ x"${postResultPass}" != x"" ]; then
      echo -e "\033[32m成功更新 kuboard-admin Token\033[0m ${KUBOARD_ENDPOINT}/kuboard-api/cluster/${KUBOARD_K8S_CLUSTER_NAME}/kind/KubernetesClusterToken"
    else
      echo -e "\033[31m访问 kuboard-server 失败\033[0m ${KUBOARD_ENDPOINT}/kuboard-api/cluster/${KUBOARD_K8S_CLUSTER_NAME}/kind/KubernetesClusterToken"
      echo ${postResult}
      exit 1
    fi
    
    
    echo " "
    echo -e "\033[36mStart Kuboard Agent\033[0m"
    
    if [ x"${agent_endpoint_count}" = "x0" ]; then
      kuboard-agent -c /etc/kuboard/kuboard-agent.ini &
    else
      for i in `seq 1 $agent_endpoint_count`
      do
        kuboard-agent -c /kuboard-agent-${i}.ini &
        echo "started \"kuboard-agent -c /kuboard-agent-${i}.ini &\""
      done
    fi
    
    echo " "
    echo -e "\033[36mShow DNS resolve config\033[0m"
    
    nameserver=''
    
    if [ -n "${KUBE_DNS_SERVICE_HOST}" ]; then
      echo "DNS from env: ${KUBE_DNS_SERVICE_HOST}:${KUBE_DNS_SERVICE_PORT}"
      nameserver=${KUBE_DNS_SERVICE_HOST}:${KUBE_DNS_SERVICE_PORT}
      echo "nameserver is resolved from \${KUBE_DNS_SERVICE_HOST}:\${KUBE_DNS_SERVICE_PORT} ${nameserver}"
    else
      echo ">>>>>>/etc/resolv.conf"
      cat /etc/resolv.conf
      echo "<<<<<</etc/resolv.conf"
      echo " "
      # 改动这两行
      echo $(sed -n '/nameserver/p' /etc/resolv.conf | head -n 1)
      nameserver=$(sed -n '/nameserver/p' /etc/resolv.conf | head -n 1)
      nameserver=${nameserver:11}
      echo "nameserver is resolved from /etc/resolv.conf, and value is ${nameserver}"
    fi
    
    echo " "
    echo -e "\033[36mStart kagent\033[0m"
    ./kagent &
    
    echo " "
    echo -e "\033[36mStart nginx\033[0m"
    echo "nameserver is [${nameserver}]"
    
    sed -i s/NAMESERVER/${nameserver}/g /etc/nginx/conf.d/nginx.80.conf
    
    nginx -g "daemon off;"
```
修改下发的两个 Deployment
```
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    k8s.kuboard.cn/ingress: "false"
    k8s.kuboard.cn/service: none
    k8s.kuboard.cn/workload: kuboard-agent-klq80z
  labels:
    k8s.kuboard.cn/name: kuboard-agent-klq80z
  name: kuboard-agent-klq80z
  namespace: kuboard
spec:
......
          image: "eipwork/kuboard-agent:v3"
          command: ["/bin/sh","/start-kuboard-agent2.sh"]
          imagePullPolicy: Always
          volumeMounts:
            - name: kuboard-agent-start-script
              mountPath: /start-kuboard-agent2.sh
              subPath: start-kuboard-agent.sh
          name: kuboard-agent
      restartPolicy: Always
      volumes:
        - name: kuboard-agent-start-script
          configMap:
            name: kuboard-agent-start-script

---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    k8s.kuboard.cn/ingress: "false"
    k8s.kuboard.cn/service: none
    k8s.kuboard.cn/workload: kuboard-agent-klq80z-2
  labels:
    k8s.kuboard.cn/name: kuboard-agent-klq80z-2
  name: kuboard-agent-klq80z-2
  namespace: kuboard
spec:
......
          image: "eipwork/kuboard-agent:v3"
          command: ["/bin/sh","/start-kuboard-agent2.sh"]
          volumeMounts:
            - name: kuboard-agent-start-script
              mountPath: /start-kuboard-agent2.sh
              subPath: start-kuboard-agent.sh
          name: kuboard-agent
          imagePullPolicy: Always
      restartPolicy: Always
      volumes:
        - name: kuboard-agent-start-script
          configMap:
            name: kuboard-agent-start-script
```
